### ISSUE TITLE
Cannot decode byte '\x72': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

### ISSUE THREAD

**Issue by Tug** [jaspervdj/number-six#32]
Just tried you bot, looks awesome!

It crashed after a few lines on a french channel though with this error message:
```
Cannot decode byte '\x72': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```

**Comment by jaspervdj** [comment]
Number Six only supports UTF-8. The French IRC channel must be using some other encoding, like ISO 8859-1.
